###
POST http://localhost:3000/beneficiarios HTTP/1.1
Content-Type: application/json

{   
    "identificacion": 1031940291,
    "nombre": "camilooo",
    "telefono": 201002,
    "correoElectronico": "ccasasss0625@gmail.com",
    "cantidadFamiliares": 5
}

###
DELETE  http://localhost:3002/beneficiarios/665f7110f9f268fed51f9e0e HTTP/1.1
Content-Type: application/json


